// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFPjZsUTIVsnP141liVd1cpt0oYMniVgk',
    appId: '1:486585603701:web:f88fe759bb50ff5f690a3c',
    messagingSenderId: '486585603701',
    projectId: 'project-tasker-app',
    authDomain: 'project-tasker-app.firebaseapp.com',
    storageBucket: 'project-tasker-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKykrtCoxC4ht5zur17haeoKn1x5-DWP4',
    appId: '1:486585603701:android:5c170cf5aba8112e690a3c',
    messagingSenderId: '486585603701',
    projectId: 'project-tasker-app',
    storageBucket: 'project-tasker-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgyD-aMXrFQuFtCCc4250HvPgXN8wdjhc',
    appId: '1:486585603701:ios:c3e5e2af9cd36ef0690a3c',
    messagingSenderId: '486585603701',
    projectId: 'project-tasker-app',
    storageBucket: 'project-tasker-app.appspot.com',
    iosClientId: '486585603701-o8n9n8m0f4bm2q8eo8u20f1k2uii67jb.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectTasker',
  );
}
